apiVersion: apps/v1
kind: Deployment
metadata:
  name: famousapp-famouschart
spec:
  replicas: 5
  template:
    spec:
      containers:
        - name: famouschart
          resources:
            limits:
              cpu: "500m"
              memory: "256Mi"

