apiVersion: apps/v1
kind: Deployment
metadata:
  name: famousapp-famouschart
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: famouschart
          resources:
            limits:
              cpu: "250m"
              memory: "128Mi"

